language: csharp
solution: Unosquare.Sparkfun.FingerprintScanner.sln
dotnet: 2.2.101
dist: xenial
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
install:
  - msbuild /t:Restore
script:
  - msbuild /p:Configuration=Release
